node {

    withMaven {

        stage('Checkout') {
            git url: 'https://github.com/sang555/demojenkins.git', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

        }

        
    }

}
