node {

    withMaven {

        stage('Checkout') {
            git url: 'https://github.com/sang555/demojenkins.git', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

        }

        stage('Image') {
            dir ('discovery-service') {
                def app = docker.build "localhost:5000/eureka:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/eureka:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }

        stage ('Final') {
            build job: 'account-service-pipeline', wait: false
        }      

    }

}
